recipe: default.v1
language: vi

pipeline:
  - name: preprocesser.VietnamesePreprocesser
  - name: HFTranformersNLP
    model_name: bert
    model_weights: bert-base-uncased
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.65
    ambiguity_threshold: 0.1
